### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 ()

### ISSUE THREAD

**Issue by maguayo** [flareact/flareact#155] opened 2021-05-09 11:27 UTC
### Describe the problem:

Getting 500 from static urls in dev and in production

<img width="1767" alt="Screenshot 2021-05-09 at 13 26 29" src="https://user-images.githubusercontent.com/1219539/117570418-4c9a6000-b0ca-11eb-8b7b-2cf52540d7c5.png">

### Link to a minimal reproduction:

Using the example and template

**Comment by tj-kev** [comment] 2021-05-10 09:09
If you run the request in the workers quick edit console what is the output from the provided console?

**Comment by samuelcolvin** [comment] 2021-05-10 12:03
I got the same errors. For me it was because I was accessing the site on `http://127.0.0.1:8787` instead of `http://localhost:8080`.

It's an easy mistake to make from the output of `yarn dev`:
```
~/code/donkey-simple 0 ➤ yarn dev    
yarn run v1.22.5
$ flareact dev
🚀 Starting Flareact dev server on http://localhost:8080 ...

[worker] 🌀  Using namespace for Workers Site "__donkey-simple-workers_sites_assets_preview"
[worker] ✨  Success
[worker] 👂  Listening on http://127.0.0.1:8787
[worker] 🌀  Detected changes...
[worker] 💁  Ignoring stale first change
[worker] 🌀  Detected changes...
[worker] 🌀  Using namespace for Workers Site "__donkey-simple-workers_sites_assets_preview"
[worker] ✨  Success
[worker] [2021-05-10 12:59:53] GET donkey-simple.samuelcolvin.workers.dev/ HTTP/1.1 200 OK
...
```

Here's some details of the 500 error:
```
~ 0 ➤ http http://127.0.0.1:8787/webpack.js
HTTP/1.1 500 Internal Server Error
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
cf-ray: 64d3026dbc802c36-FRA
cf-request-id: 09f7bfd89100002c365c86d000000001
content-length: 51
content-type: text/plain;charset=UTF-8
date: Mon, 10 May 2021 12:00:50 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
nel: {"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=SzCHVFGuMURBEDhtJIOEt6Solg%2FThOmXTLI5hRN3HVN7l3q5D1xj1CX%2BMjGi6%2Fqqgs8N3DCMEqli%2BrEQxpnF8SbxRhfgoIMJ1%2BZUfCUoZeud3g0yVw7VllGF2wzVHlp3hPBaVNQpM4Jg%2BNIZdAlJvnBXrw%3D%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
vary: Accept-Encoding

could not find webpack.js in your content namespace

```

**Comment by samuelcolvin** [comment] 2021-05-10 12:52
Here are the paths with errors:

```
[worker] [2021-05-10 12:44:33] GET donkey-simple.samuelcolvin.workers.dev/ HTTP/1.1 200 OK
[worker] [2021-05-10 12:44:34] GET donkey-simple.samuelcolvin.workers.dev/webpack.js HTTP/1.1 500 Internal Server Error
[worker] [2021-05-10 12:44:34] GET donkey-simple.samuelcolvin.workers.dev/pages/_app.js HTTP/1.1 500 Internal Server Error
[worker] [2021-05-10 12:44:34] GET donkey-simple.samuelcolvin.workers.dev/pages/index.js HTTP/1.1 500 Internal Server Error
[worker] [2021-05-10 12:44:34] GET donkey-simple.samuelcolvin.workers.dev/main.js HTTP/1.1 500 Internal Server Error
[worker] [2021-05-10 12:44:34] GET donkey-simple.samuelcolvin.workers.dev/pages/_app.js HTTP/1.1 500 Internal Server Error
[worker] [2021-05-10 12:44:34] GET donkey-simple.samuelcolvin.workers.dev/pages/index.js HTTP/1.1 500 Internal Server Error
[worker] [2021-05-10 12:44:35] GET donkey-simple.samuelcolvin.workers.dev/favicon.ico HTTP/1.1 500 Internal Server Error
```

**Comment by traffisco** [comment] 2021-05-10 12:59
> Here are the paths with errors:
> 
> ```
> [worker] [2021-05-10 12:44:33] GET donkey-simple.samuelcolvin.workers.dev/ HTTP/1.1 200 OK
> [worker] [2021-05-10 12:44:34] GET donkey-simple.samuelcolvin.workers.dev/webpack.js HTTP/1.1 500 Internal Server Error
> [worker] [2021-05-10 12:44:34] GET donkey-simple.samuelcolvin.workers.dev/pages/_app.js HTTP/1.1 500 Internal Server Error
> [worker] [2021-05-10 12:44:34] GET donkey-simple.samuelcolvin.workers.dev/pages/index.js HTTP/1.1 500 Internal Server Error
> [worker] [2021-05-10 12:44:34] GET donkey-simple.samuelcolvin.workers.dev/main.js HTTP/1.1 500 Internal Server Error
> [worker] [2021-05-10 12:44:34] GET donkey-simple.samuelcolvin.workers.dev/pages/_app.js HTTP/1.1 500 Internal Server Error
> [worker] [2021-05-10 12:44:34] GET donkey-simple.samuelcolvin.workers.dev/pages/index.js HTTP/1.1 500 Internal Server Error
> [worker] [2021-05-10 12:44:35] GET donkey-simple.samuelcolvin.workers.dev/favicon.ico HTTP/1.1 500 Internal Server Error
> ```

Yes, it should be `https://donkey-simple.samuelcolvin.workers.dev/_flareact/static/webpack.js`

**Comment by jplhomer** [comment] 2021-05-10 13:16
May have been fixed in #154 which I just merged into the main branch. Please let me know if that worked!

**Comment by tj-kev** [comment] 2021-05-13 15:36
This solved the issue for me. @maguayo can you confirm its now working for you?

**Comment by samuelcolvin** [comment] 2021-05-22 17:03
This is still happening for me with v1.2.1.

**Comment by tj-kev** [comment] 2021-05-25 08:55
Strange. The ```/``` is still missing after ```static``` in the path?

**Comment by maguayo** [comment] 2021-05-25 12:13
Still not working :S

**Comment by tj-kev** [comment] 2021-05-25 12:37
@samuelcolvin @maguayo 

Is this when using the local dev?

Are you using port 8787 or 8080?

**Comment by samuelcolvin** [comment] 2021-05-25 12:54
> Is this when using the local dev?

yes 

> Are you using port 8787 or 8080?

Both I think.

**Comment by tj-kev** [comment] 2021-05-26 12:33
Sorry I'm unable to replicate this. Would you be able to provide a sample repo with the problem?

**Comment by maguayo** [comment] 2021-05-26 15:18
Same for me. Its using the standard template

**Comment by tj-kev** [comment] 2021-05-29 19:52
Done a bit more testing on a fresh copy of the template cloned directly from the repo. Running locally using the ```npm run dev ``` command.

### Browser output when accessing from localhost:8080
![browser-8080](https://user-images.githubusercontent.com/15669671/120083095-59edad80-c0be-11eb-9f6a-4db3872f20ac.JPG)

### CLI output from accessing from localhost:8080
![run-dev-8080](https://user-images.githubusercontent.com/15669671/120083225-0b8cde80-c0bf-11eb-899e-c918659ad3df.JPG)


No issues except for the missing favicon file. I also added the public folder which isn't provided as part of the template. I also tried the same thing with ```localhost:8787```


### Browser output when accessing from localhost:8787
![browser-8787](https://user-images.githubusercontent.com/15669671/120083249-4858d580-c0bf-11eb-9e0f-4a2ac44646f7.JPG)

### CLI output from accessing from localhost:8787
![run-dev-8787](https://user-images.githubusercontent.com/15669671/120083258-5870b500-c0bf-11eb-9314-5e13e40a4bb0.JPG)


Using port 8787 does give errors but this is expected. Hope this helps.

**Comment by vndre** [comment] 2021-05-30 23:41
Any update on this? This should be a critical bug, basically you can't use the template because is broken.

**Comment by tj-kev** [comment] 2021-06-01 10:19
> Any update on this? This should be a critical bug, you can't use the template because is broken.

Sorry I've tried to replicate. On my previous post I shown examples of it working on :8080 but not :8787. This is expected behaviour. If you are still having issues I need more information about the issue. Console output, browser output etc.

**Comment by vndre** [comment] 2021-06-01 14:18
> > Any update on this? This should be a critical bug, you can't use the template because is broken.
> 
> Sorry I've tried to replicate. On my previous post I shown examples of it working on :8080 but not :8787. This is expected behaviour. If you are still having issues I need more information about the issue. Console output, browser output etc.
> 
> Edit: Also are you getting the error on local dev, workers dev or production? Have you got the template through git clone or the wrangler cli? What OS are you using?

Hello, sorry it was my mistake it wasn't working. For some reason I wasn't able to open the app on port 8080 so I thought 8787 was the only address. After some reconfiguration I noticed my local nodejs was updated to v16, I then removed node_modules and couldn't built it up! I found a non-related issue comment that says `node-fibers` is not yet supported in that version...

So using node v15 I reinstalled all deps and now the app is working normal in 8080, thank you.

**Comment by tj-kev** [comment] 2021-06-01 14:51
> > > Any update on this? This should be a critical bug, you can't use the template because is broken.
> > 
> > 
> > Sorry I've tried to replicate. On my previous post I shown examples of it working on :8080 but not :8787. This is expected behaviour. If you are still having issues I need more information about the issue. Console output, browser output etc.
> > Edit: Also are you getting the error on local dev, workers dev or production? Have you got the template through git clone or the wrangler cli? What OS are you using?
> 
> Hello, sorry it was my mistake it wasn't working. For some reason I wasn't able to open the app on port 8080 so I thought 8787 was the only address. After some reconfiguration I noticed my local nodejs was updated to v16, I then removed node_modules and couldn't built it up! I found a non-related issue comment that says `node-fibers` is not yet supported in that version...
> 
> So using node v15 I reinstalled all deps and now the app is working normal in 8080, thank you.

Thanks for the update. Happy its working for you! :)

**Comment by kkeene1** [comment] 2021-06-01 14:53
Have also tested with a fresh clone of the template and works fine on port 8080.

**Comment by tj-kev** [comment] 2021-07-31 22:23
Closing this as I couldn't replicate the issue and no further updates provided. If still a problem I can open the issue again.

**Closed by tj-kev** 2021-07-31 22:23 UTC
